version: '3'
services:
  mysql-db:
    image: "mariadb:10.4"
    container_name: mysql-db
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=hippo
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mysql-db-data:/var/lib/mysql
      - ./mysql/m1.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3308:3306
    networks:
      mysql-net:
        ipv4_address: 172.20.0.11
  mysql-db-r1:
    image: "mariadb:10.4"
    container_name: mysql-db-r1
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=hippo
      - MYSQL_ROOT_PASSWORD=toor
    depends_on:
      - mysql-db
    volumes:
      - mysql-db-r1-data:/var/lib/mysql
      - ./mysql/r1.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3311:3306
    networks:
      mysql-net:
        ipv4_address: 172.20.0.21
  mysql-db-r2:
    image: "mariadb:10.4"
    container_name: mysql-db-r2
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=hippo
      - MYSQL_ROOT_PASSWORD=toor
    depends_on:
      - mysql-db-r1
    volumes:
      - mysql-db-r2-data:/var/lib/mysql
      - ./mysql/r2.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3312:3306
    networks:
      mysql-net:
        ipv4_address: 172.20.0.22
  mysql-db-r3:
    image: "mariadb:10.4"
    container_name: mysql-db-r3
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=hippo
      - MYSQL_ROOT_PASSWORD=toor
    depends_on:
      - mysql-db-r1
    volumes:
      - mysql-db-r3-data:/var/lib/mysql
      - ./mysql/r3.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3313:3306
    networks:
      mysql-net:
        ipv4_address: 172.20.0.23
  mysql-db-test:
    image: "mariadb:10.4"
    container_name: mysql-db-test
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=hippo_test
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3307:3306
    networks:
      mysql-net:
        ipv4_address: 172.20.0.99
  phpmyadmin:
    image: "phpmyadmin:5.2"
    container_name: phpmyadmin
    restart: always
    ports:
      - 8010:80
    environment:
      - PMA_HOSTS=mysql-db,mysql-db-r1,mysql-db-r2,mysql-db-r3,mysql-db-test
    depends_on:
      - mysql-db
      - mysql-db-r1
      - mysql-db-r2
      - mysql-db-r3
      - mysql-db-test
    networks:
      mysql-net:
        ipv4_address: 172.20.0.101
  mongo-db-1:
    image: "mongo:4.4"
    container_name: mongo-db-1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=123456
      - MONGO_INITDB_DATABASE=hippo
    volumes:
      - mongo-db-1-data:/data/db
      - ./mongo/mongodb.key:/data/auth/mongodb.key
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./mongo/rs-init.sh:/data/script/rs-init.sh
    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /data/auth/mongodb.key
          chown 999:999 /data/auth/mongodb.key
          exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --port 27031 --replSet rs-hippo --keyFile /data/auth/mongodb.key
    ports:
      - 27031:27031
    networks:
      mongo-net:
        ipv4_address: 172.30.0.11
  mongo-db-2:
    image: "mongo:4.4"
    container_name: mongo-db-2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=123456
      - MONGO_INITDB_DATABASE=hippo
    volumes:
      - mongo-db-2-data:/data/db
      - ./mongo/mongodb.key:/data/auth/mongodb.key
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /data/auth/mongodb.key
          chown 999:999 /data/auth/mongodb.key
          exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --port 27032 --replSet rs-hippo --keyFile /data/auth/mongodb.key
    ports:
      - 27032:27032
    networks:
      mongo-net:
        ipv4_address: 172.30.0.12
  mongo-db-3:
    image: "mongo:4.4"
    container_name: mongo-db-3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=123456
      - MONGO_INITDB_DATABASE=hippo
    volumes:
      - mongo-db-3-data:/data/db
      - ./mongo/mongodb.key:/data/auth/mongodb.key
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /data/auth/mongodb.key
          chown 999:999 /data/auth/mongodb.key
          exec docker-entrypoint.sh $$@
    command: mongod --bind_ip_all --port 27033 --replSet rs-hippo --keyFile /data/auth/mongodb.key
    ports:
      - 27033:27033
    networks:
      mongo-net:
        ipv4_address: 172.30.0.13
  mongo-test-db:
    image: "mongo:4.4"
    container_name: mongo-test-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=123456
      - MONGO_INITDB_DATABASE=hippo_test
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 27020:27017
    networks:
      mongo-net:
        ipv4_address: 172.30.0.99
  proxy:
    image: "haproxy:2.6"
    container_name: "haproxy"
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8020:80 # stats
      - 3300:3300 # mysql master
      - 3301:3301 # mysql replica
    networks:
      mysql-net:
        ipv4_address: 172.20.0.102
volumes:
  mysql-db-data:
  mysql-db-r1-data:
  mysql-db-r2-data:
  mysql-db-r3-data:
  mongo-db-1-data:
  mongo-db-2-data:
  mongo-db-3-data:
networks:
  mysql-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  mongo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16