version: '3'
services:
  mysql-db:
    image: "mariadb:10.4"
    container_name: mysql-db
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=goseidon_local
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mysql-db-data:/var/lib/mysql
      - ./mysql/m1.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3308:3306
  mysql-db-r1:
    image: "mariadb:10.4"
    container_name: mysql-db-r1
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=goseidon_local
      - MYSQL_ROOT_PASSWORD=toor
    depends_on:
      - mysql-db
    volumes:
      - mysql-db-r1-data:/var/lib/mysql
      - ./mysql/r1.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3311:3306
  mysql-db-r2:
    image: "mariadb:10.4"
    container_name: mysql-db-r2
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=goseidon_local
      - MYSQL_ROOT_PASSWORD=toor
    depends_on:
      - mysql-db-r1
    volumes:
      - mysql-db-r2-data:/var/lib/mysql
      - ./mysql/r2.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3312:3306
  mysql-db-test:
    image: "mariadb:10.4"
    container_name: mysql-db-test
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=goseidon_local_test
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3307:3306
  phpmyadmin:
    image: "phpmyadmin:5.2"
    container_name: phpmyadmin
    restart: always
    ports:
      - 8010:80
    environment:
      - PMA_HOSTS=mysql-db,mysql-db-r1,mysql-db-r2,mysql-db-test
    depends_on:
      - mysql-db
      - mysql-db-r1
      - mysql-db-r2
      - mysql-db-test
volumes:
  mysql-db-data:
  mysql-db-r1-data:
  mysql-db-r2-data: