openapi: "3.0.0"
info:
  title: Hippo Specification
  version: 0.0.1-$REVISION
  description: Hippo server for goseidon
  contact:
    name: Support
    url: https://github.com/go-seidon/
    email: raka.suryaardi@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000/
    description: local
paths:
  /:
    $ref: "./path/info.yml"
  /health:
    $ref: "./path/health.yml"
  /v1/file:
    $ref: "./path/file.yml"
  /v1/file/{id}:
    $ref: "./path/file_id.yml"
components:
  parameters:
    ObjectId: 
      $ref: "./parameter/object_id.yml"
    CorrelationId: 
      $ref: "./parameter/correlation_id.yml"
  schemas:
    ResponseBodyInfo:
      $ref: "./schema/response_body_info.yml"

    GetAppInfoResponse:
      $ref: "./operation/get-app-info/response_body.yml"
    GetAppInfoData:
      $ref: "./operation/get-app-info/response_data.yml"

    CheckHealthResponse:
      $ref: "./operation/check-health/response_body.yml"
    CheckHealthData:
      $ref: "./operation/check-health/response_data.yml"
    CheckHealthDetail:
      $ref: "./operation/check-health/response_detail.yml"

    DeleteFileResponse:
      $ref: "./operation/delete-file-by-id/response_body.yml"
    DeleteFileData:
      $ref: "./operation/delete-file-by-id/response_data.yml"

    RetrieveFileResponse:
      $ref: "./operation/retrieve-file-by-id/response_body.yml"

    UploadFileRequest:
      $ref: "./operation/upload-file/request_body.yml"
    UploadFileResponse:
      $ref: "./operation/upload-file/response_body.yml"
    UploadFileData:
      $ref: "./operation/upload-file/response_data.yml"

  responses:
    BadRequest:
      $ref: "./response/bad_request.yml"
    UnauthenticatedAccess:
      $ref: "./response/unauthenticated_access.yml"
    NotFound:
      $ref: "./response/not_found.yml"
    ServerError:
      $ref: "./response/server_error.yml"

  securitySchemes:
    basicAuth:
      $ref: "./security/basic.yml"
