version: '3'
services:
  mysql-db:
    image: "mariadb:10.4"
    container_name: mysql-db
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=goseidon_local
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - "3308:3306"
  mysql-db-test:
    image: "mariadb:10.4"
    container_name: mysql-db-test
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=goseidon_local_test
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3307:3306"
  phpmyadmin:
    image: "phpmyadmin:5.2"
    container_name: phpmyadmin
    restart: always
    ports:
      - 8010:80
    environment:
      - PMA_HOSTS=mysql-db,mysql-db-test
    depends_on:
      - mysql-db
      - mysql-db-test
volumes:
  mysql-db-data: