// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/grpcapp/file.proto

package grpcapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteFileParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *DeleteFileParam) Reset() {
	*x = DeleteFileParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileParam) ProtoMessage() {}

func (x *DeleteFileParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileParam.ProtoReflect.Descriptor instead.
func (*DeleteFileParam) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteFileParam) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *DeleteFileData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteFileResult) Reset() {
	*x = DeleteFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResult) ProtoMessage() {}

func (x *DeleteFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResult.ProtoReflect.Descriptor instead.
func (*DeleteFileResult) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteFileResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteFileResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteFileResult) GetData() *DeleteFileData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteFileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedAt int64 `protobuf:"varint,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *DeleteFileData) Reset() {
	*x = DeleteFileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileData) ProtoMessage() {}

func (x *DeleteFileData) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileData.ProtoReflect.Descriptor instead.
func (*DeleteFileData) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFileData) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type RetrieveFileParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *RetrieveFileParam) Reset() {
	*x = RetrieveFileParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveFileParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveFileParam) ProtoMessage() {}

func (x *RetrieveFileParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveFileParam.ProtoReflect.Descriptor instead.
func (*RetrieveFileParam) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveFileParam) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type RetrieveFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Chunks  []byte `protobuf:"bytes,3,opt,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *RetrieveFileResult) Reset() {
	*x = RetrieveFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveFileResult) ProtoMessage() {}

func (x *RetrieveFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveFileResult.ProtoReflect.Descriptor instead.
func (*RetrieveFileResult) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveFileResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RetrieveFileResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetrieveFileResult) GetChunks() []byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type UploadFileParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*UploadFileParam_Chunks
	//	*UploadFileParam_Info
	Data isUploadFileParam_Data `protobuf_oneof:"data"`
}

func (x *UploadFileParam) Reset() {
	*x = UploadFileParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFileParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileParam) ProtoMessage() {}

func (x *UploadFileParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileParam.ProtoReflect.Descriptor instead.
func (*UploadFileParam) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{5}
}

func (m *UploadFileParam) GetData() isUploadFileParam_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadFileParam) GetChunks() []byte {
	if x, ok := x.GetData().(*UploadFileParam_Chunks); ok {
		return x.Chunks
	}
	return nil
}

func (x *UploadFileParam) GetInfo() *UploadFileInfo {
	if x, ok := x.GetData().(*UploadFileParam_Info); ok {
		return x.Info
	}
	return nil
}

type isUploadFileParam_Data interface {
	isUploadFileParam_Data()
}

type UploadFileParam_Chunks struct {
	Chunks []byte `protobuf:"bytes,1,opt,name=chunks,proto3,oneof"`
}

type UploadFileParam_Info struct {
	Info *UploadFileInfo `protobuf:"bytes,2,opt,name=info,proto3,oneof"`
}

func (*UploadFileParam_Chunks) isUploadFileParam_Data() {}

func (*UploadFileParam_Info) isUploadFileParam_Data() {}

type UploadFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mimetype  string `protobuf:"bytes,2,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Extension string `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (x *UploadFileInfo) Reset() {
	*x = UploadFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileInfo) ProtoMessage() {}

func (x *UploadFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileInfo.ProtoReflect.Descriptor instead.
func (*UploadFileInfo) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{6}
}

func (x *UploadFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileInfo) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *UploadFileInfo) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type UploadFileResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *UploadFileData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadFileResult) Reset() {
	*x = UploadFileResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResult) ProtoMessage() {}

func (x *UploadFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResult.ProtoReflect.Descriptor instead.
func (*UploadFileResult) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{7}
}

func (x *UploadFileResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadFileResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileResult) GetData() *UploadFileData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path       string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Mimetype   string `protobuf:"bytes,4,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Extension  string `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	Size       int64  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	UploadedAt int64  `protobuf:"varint,7,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
}

func (x *UploadFileData) Reset() {
	*x = UploadFileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpcapp_file_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileData) ProtoMessage() {}

func (x *UploadFileData) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpcapp_file_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileData.ProtoReflect.Descriptor instead.
func (*UploadFileData) Descriptor() ([]byte, []int) {
	return file_api_grpcapp_file_proto_rawDescGZIP(), []int{8}
}

func (x *UploadFileData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadFileData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadFileData) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *UploadFileData) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *UploadFileData) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadFileData) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

var File_api_grpcapp_file_proto protoreflect.FileDescriptor

var file_api_grpcapp_file_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x70, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x22, 0x2a, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x6d, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2c, 0x0a,
	0x11, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x12, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x62, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x06, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5e, 0x0a, 0x0e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x10, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb7, 0x01, 0x0a, 0x0e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x41, 0x74, 0x32, 0xe0, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x18, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x19, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x49, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x1a, 0x1b, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x30, 0x01, 0x12, 0x43, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x18, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x19, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x28, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpcapp_file_proto_rawDescOnce sync.Once
	file_api_grpcapp_file_proto_rawDescData = file_api_grpcapp_file_proto_rawDesc
)

func file_api_grpcapp_file_proto_rawDescGZIP() []byte {
	file_api_grpcapp_file_proto_rawDescOnce.Do(func() {
		file_api_grpcapp_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpcapp_file_proto_rawDescData)
	})
	return file_api_grpcapp_file_proto_rawDescData
}

var file_api_grpcapp_file_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_grpcapp_file_proto_goTypes = []interface{}{
	(*DeleteFileParam)(nil),    // 0: file.v1.DeleteFileParam
	(*DeleteFileResult)(nil),   // 1: file.v1.DeleteFileResult
	(*DeleteFileData)(nil),     // 2: file.v1.DeleteFileData
	(*RetrieveFileParam)(nil),  // 3: file.v1.RetrieveFileParam
	(*RetrieveFileResult)(nil), // 4: file.v1.RetrieveFileResult
	(*UploadFileParam)(nil),    // 5: file.v1.UploadFileParam
	(*UploadFileInfo)(nil),     // 6: file.v1.UploadFileInfo
	(*UploadFileResult)(nil),   // 7: file.v1.UploadFileResult
	(*UploadFileData)(nil),     // 8: file.v1.UploadFileData
}
var file_api_grpcapp_file_proto_depIdxs = []int32{
	2, // 0: file.v1.DeleteFileResult.data:type_name -> file.v1.DeleteFileData
	6, // 1: file.v1.UploadFileParam.info:type_name -> file.v1.UploadFileInfo
	8, // 2: file.v1.UploadFileResult.data:type_name -> file.v1.UploadFileData
	0, // 3: file.v1.FileService.DeleteFile:input_type -> file.v1.DeleteFileParam
	3, // 4: file.v1.FileService.RetrieveFile:input_type -> file.v1.RetrieveFileParam
	5, // 5: file.v1.FileService.UploadFile:input_type -> file.v1.UploadFileParam
	1, // 6: file.v1.FileService.DeleteFile:output_type -> file.v1.DeleteFileResult
	4, // 7: file.v1.FileService.RetrieveFile:output_type -> file.v1.RetrieveFileResult
	7, // 8: file.v1.FileService.UploadFile:output_type -> file.v1.UploadFileResult
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_grpcapp_file_proto_init() }
func file_api_grpcapp_file_proto_init() {
	if File_api_grpcapp_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpcapp_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveFileParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFileParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFileResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpcapp_file_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_grpcapp_file_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*UploadFileParam_Chunks)(nil),
		(*UploadFileParam_Info)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpcapp_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpcapp_file_proto_goTypes,
		DependencyIndexes: file_api_grpcapp_file_proto_depIdxs,
		MessageInfos:      file_api_grpcapp_file_proto_msgTypes,
	}.Build()
	File_api_grpcapp_file_proto = out.File
	file_api_grpcapp_file_proto_rawDesc = nil
	file_api_grpcapp_file_proto_goTypes = nil
	file_api_grpcapp_file_proto_depIdxs = nil
}
