APP_NAME = "hippo"
APP_ENV = "local"
APP_VERSION = "1.0.0"
APP_DEBUG = true

REST_APP_HOST = "localhost"
REST_APP_PORT = 3000
GRPC_APP_HOST = "localhost"
GRPC_APP_PORT = 5000

DB_PROVIDER = "mysql"

MYSQL_MASTER_HOST = "localhost"
MYSQL_MASTER_PORT = 3300
MYSQL_MASTER_USER = "admin"
MYSQL_MASTER_PASSWORD = "123456"
MYSQL_MASTER_DB_NAME = "hippo"

MYSQL_REPLICA_HOST = "localhost"
MYSQL_REPLICA_PORT = 3301
MYSQL_REPLICA_USER = "admin"
MYSQL_REPLICA_PASSWORD = "123456"
MYSQL_REPLICA_DB_NAME = "hippo"

MONGO_MODE = "replication"
MONGO_DB_NAME = "hippo"
MONGO_AUTH_MODE = "basic"
MONGO_AUTH_USER = "admin"
MONGO_AUTH_PASSWORD = "123456"
MONGO_AUTH_SOURCE = "hippo"
MONGO_STANDALONE_HOST = "localhost"
MONGO_STANDALONE_PORT = 27031
MONGO_REPLICA_NAME = "rs-hippo"
MONGO_REPLICA_HOSTS = ["mongo-db-1:27031", "mongo-db-2:27032", "mongo-db-3:27033"]

UPLOAD_FORM_SIZE = 1073741824
UPLOAD_DIRECTORY = "storage"
