APP_NAME = "goseidon-local"
APP_ENV = "local"
APP_VERSION = "1.0.0"

REST_APP_HOST = "localhost"
REST_APP_PORT = 3000
RPC_APP_HOST = "localhost"
RPC_APP_PORT = 5000

DB_PROVIDER = "mysql"

MYSQL_HOST = "localhost"
MYSQL_PORT = 3308
MYSQL_USER = "admin"
MYSQL_PASSWORD = "123456"
MYSQL_DB_NAME = "goseidon_local"
