APP_NAME = "goseidon-local"
APP_ENV = "local"
APP_VERSION = "1.0.0"
APP_DEBUG = true

REST_APP_HOST = "localhost"
REST_APP_PORT = 3001
RPC_APP_HOST = "localhost"
RPC_APP_PORT = 5001

DB_PROVIDER = "mysql"

MYSQL_MASTER_HOST = "localhost"
MYSQL_MASTER_PORT = 3307
MYSQL_MASTER_USER = "admin"
MYSQL_MASTER_PASSWORD = "123456"
MYSQL_MASTER_DB_NAME = "goseidon_local_test"

MYSQL_REPLICA_HOST = "localhost"
MYSQL_REPLICA_PORT = 3307
MYSQL_REPLICA_USER = "admin"
MYSQL_REPLICA_PASSWORD = "123456"
MYSQL_REPLICA_DB_NAME = "goseidon_local_test"

MONGO_HOST = "localhost"
MONGO_PORT = 27020
MONGO_USER = "admin"
MONGO_PASSWORD = "123456"
MONGO_DB_NAME = "goseidon_local"

UPLOAD_FORM_SIZE = 1073741824
UPLOAD_DIRECTORY = "storage"
