APP_NAME = "hippo"
APP_ENV = "local"
APP_VERSION = "1.0.0"
APP_DEBUG = true

REST_APP_HOST = "localhost"
REST_APP_PORT = 20120
GRPC_APP_HOST = "localhost"
GRPC_APP_PORT = 5001

REPOSITORY_PROVIDER = "mysql"

MYSQL_MASTER_HOST = "localhost"
MYSQL_MASTER_PORT = 3307
MYSQL_MASTER_USER = "admin"
MYSQL_MASTER_PASSWORD = "123456"
MYSQL_MASTER_DB_NAME = "hippo_test"

MYSQL_REPLICA_HOST = "localhost"
MYSQL_REPLICA_PORT = 3307
MYSQL_REPLICA_USER = "admin"
MYSQL_REPLICA_PASSWORD = "123456"
MYSQL_REPLICA_DB_NAME = "hippo_test"

MONGO_MODE = "standalone"
MONGO_DB_NAME = "hippo_test"
MONGO_AUTH_MODE = "basic"
MONGO_AUTH_USER = "admin"
MONGO_AUTH_PASSWORD = "123456"
MONGO_AUTH_SOURCE = "hippo_test"
MONGO_STANDALONE_HOST = "localhost"
MONGO_STANDALONE_PORT = 27020
MONGO_REPLICA_NAME = ""
MONGO_REPLICA_HOSTS = []

UPLOAD_FORM_SIZE = 1073741824
UPLOAD_DIRECTORY = "storage"
