// Code generated by MockGen. DO NOT EDIT.
// Source: api/grpcapp/file_grpc.pb.go

// Package mock_grpcapp is a generated GoMock package.
package mock_grpcapp

import (
	context "context"
	reflect "reflect"

	grpcapp "github.com/go-seidon/hippo/api/grpcapp"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockFileServiceClient is a mock of FileServiceClient interface.
type MockFileServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceClientMockRecorder
}

// MockFileServiceClientMockRecorder is the mock recorder for MockFileServiceClient.
type MockFileServiceClientMockRecorder struct {
	mock *MockFileServiceClient
}

// NewMockFileServiceClient creates a new mock instance.
func NewMockFileServiceClient(ctrl *gomock.Controller) *MockFileServiceClient {
	mock := &MockFileServiceClient{ctrl: ctrl}
	mock.recorder = &MockFileServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileServiceClient) EXPECT() *MockFileServiceClientMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileServiceClient) DeleteFile(ctx context.Context, in *grpcapp.DeleteFileParam, opts ...grpc.CallOption) (*grpcapp.DeleteFileResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFile", varargs...)
	ret0, _ := ret[0].(*grpcapp.DeleteFileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceClientMockRecorder) DeleteFile(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileServiceClient)(nil).DeleteFile), varargs...)
}

// RetrieveFile mocks base method.
func (m *MockFileServiceClient) RetrieveFile(ctx context.Context, in *grpcapp.RetrieveFileParam, opts ...grpc.CallOption) (grpcapp.FileService_RetrieveFileClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RetrieveFile", varargs...)
	ret0, _ := ret[0].(grpcapp.FileService_RetrieveFileClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveFile indicates an expected call of RetrieveFile.
func (mr *MockFileServiceClientMockRecorder) RetrieveFile(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveFile", reflect.TypeOf((*MockFileServiceClient)(nil).RetrieveFile), varargs...)
}

// UploadFile mocks base method.
func (m *MockFileServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpcapp.FileService_UploadFileClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadFile", varargs...)
	ret0, _ := ret[0].(grpcapp.FileService_UploadFileClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileServiceClientMockRecorder) UploadFile(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileServiceClient)(nil).UploadFile), varargs...)
}

// MockFileService_RetrieveFileClient is a mock of FileService_RetrieveFileClient interface.
type MockFileService_RetrieveFileClient struct {
	ctrl     *gomock.Controller
	recorder *MockFileService_RetrieveFileClientMockRecorder
}

// MockFileService_RetrieveFileClientMockRecorder is the mock recorder for MockFileService_RetrieveFileClient.
type MockFileService_RetrieveFileClientMockRecorder struct {
	mock *MockFileService_RetrieveFileClient
}

// NewMockFileService_RetrieveFileClient creates a new mock instance.
func NewMockFileService_RetrieveFileClient(ctrl *gomock.Controller) *MockFileService_RetrieveFileClient {
	mock := &MockFileService_RetrieveFileClient{ctrl: ctrl}
	mock.recorder = &MockFileService_RetrieveFileClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService_RetrieveFileClient) EXPECT() *MockFileService_RetrieveFileClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockFileService_RetrieveFileClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockFileService_RetrieveFileClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockFileService_RetrieveFileClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockFileService_RetrieveFileClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockFileService_RetrieveFileClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFileService_RetrieveFileClient)(nil).Context))
}

// Header mocks base method.
func (m *MockFileService_RetrieveFileClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockFileService_RetrieveFileClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockFileService_RetrieveFileClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockFileService_RetrieveFileClient) Recv() (*grpcapp.RetrieveFileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*grpcapp.RetrieveFileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockFileService_RetrieveFileClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockFileService_RetrieveFileClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockFileService_RetrieveFileClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockFileService_RetrieveFileClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFileService_RetrieveFileClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockFileService_RetrieveFileClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockFileService_RetrieveFileClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFileService_RetrieveFileClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockFileService_RetrieveFileClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockFileService_RetrieveFileClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockFileService_RetrieveFileClient)(nil).Trailer))
}

// MockFileService_UploadFileClient is a mock of FileService_UploadFileClient interface.
type MockFileService_UploadFileClient struct {
	ctrl     *gomock.Controller
	recorder *MockFileService_UploadFileClientMockRecorder
}

// MockFileService_UploadFileClientMockRecorder is the mock recorder for MockFileService_UploadFileClient.
type MockFileService_UploadFileClientMockRecorder struct {
	mock *MockFileService_UploadFileClient
}

// NewMockFileService_UploadFileClient creates a new mock instance.
func NewMockFileService_UploadFileClient(ctrl *gomock.Controller) *MockFileService_UploadFileClient {
	mock := &MockFileService_UploadFileClient{ctrl: ctrl}
	mock.recorder = &MockFileService_UploadFileClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService_UploadFileClient) EXPECT() *MockFileService_UploadFileClientMockRecorder {
	return m.recorder
}

// CloseAndRecv mocks base method.
func (m *MockFileService_UploadFileClient) CloseAndRecv() (*grpcapp.UploadFileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAndRecv")
	ret0, _ := ret[0].(*grpcapp.UploadFileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockFileService_UploadFileClientMockRecorder) CloseAndRecv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAndRecv", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).CloseAndRecv))
}

// CloseSend mocks base method.
func (m *MockFileService_UploadFileClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockFileService_UploadFileClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockFileService_UploadFileClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockFileService_UploadFileClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).Context))
}

// Header mocks base method.
func (m *MockFileService_UploadFileClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockFileService_UploadFileClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).Header))
}

// RecvMsg mocks base method.
func (m_2 *MockFileService_UploadFileClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockFileService_UploadFileClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockFileService_UploadFileClient) Send(arg0 *grpcapp.UploadFileParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockFileService_UploadFileClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockFileService_UploadFileClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockFileService_UploadFileClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockFileService_UploadFileClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockFileService_UploadFileClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockFileService_UploadFileClient)(nil).Trailer))
}

// MockFileServiceServer is a mock of FileServiceServer interface.
type MockFileServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceServerMockRecorder
}

// MockFileServiceServerMockRecorder is the mock recorder for MockFileServiceServer.
type MockFileServiceServerMockRecorder struct {
	mock *MockFileServiceServer
}

// NewMockFileServiceServer creates a new mock instance.
func NewMockFileServiceServer(ctrl *gomock.Controller) *MockFileServiceServer {
	mock := &MockFileServiceServer{ctrl: ctrl}
	mock.recorder = &MockFileServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileServiceServer) EXPECT() *MockFileServiceServerMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileServiceServer) DeleteFile(arg0 context.Context, arg1 *grpcapp.DeleteFileParam) (*grpcapp.DeleteFileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", arg0, arg1)
	ret0, _ := ret[0].(*grpcapp.DeleteFileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceServerMockRecorder) DeleteFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileServiceServer)(nil).DeleteFile), arg0, arg1)
}

// RetrieveFile mocks base method.
func (m *MockFileServiceServer) RetrieveFile(arg0 *grpcapp.RetrieveFileParam, arg1 grpcapp.FileService_RetrieveFileServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveFile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetrieveFile indicates an expected call of RetrieveFile.
func (mr *MockFileServiceServerMockRecorder) RetrieveFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveFile", reflect.TypeOf((*MockFileServiceServer)(nil).RetrieveFile), arg0, arg1)
}

// UploadFile mocks base method.
func (m *MockFileServiceServer) UploadFile(arg0 grpcapp.FileService_UploadFileServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileServiceServerMockRecorder) UploadFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileServiceServer)(nil).UploadFile), arg0)
}

// MockUnsafeFileServiceServer is a mock of UnsafeFileServiceServer interface.
type MockUnsafeFileServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeFileServiceServerMockRecorder
}

// MockUnsafeFileServiceServerMockRecorder is the mock recorder for MockUnsafeFileServiceServer.
type MockUnsafeFileServiceServerMockRecorder struct {
	mock *MockUnsafeFileServiceServer
}

// NewMockUnsafeFileServiceServer creates a new mock instance.
func NewMockUnsafeFileServiceServer(ctrl *gomock.Controller) *MockUnsafeFileServiceServer {
	mock := &MockUnsafeFileServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeFileServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeFileServiceServer) EXPECT() *MockUnsafeFileServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedFileServiceServer mocks base method.
func (m *MockUnsafeFileServiceServer) mustEmbedUnimplementedFileServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFileServiceServer")
}

// mustEmbedUnimplementedFileServiceServer indicates an expected call of mustEmbedUnimplementedFileServiceServer.
func (mr *MockUnsafeFileServiceServerMockRecorder) mustEmbedUnimplementedFileServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFileServiceServer", reflect.TypeOf((*MockUnsafeFileServiceServer)(nil).mustEmbedUnimplementedFileServiceServer))
}

// MockFileService_RetrieveFileServer is a mock of FileService_RetrieveFileServer interface.
type MockFileService_RetrieveFileServer struct {
	ctrl     *gomock.Controller
	recorder *MockFileService_RetrieveFileServerMockRecorder
}

// MockFileService_RetrieveFileServerMockRecorder is the mock recorder for MockFileService_RetrieveFileServer.
type MockFileService_RetrieveFileServerMockRecorder struct {
	mock *MockFileService_RetrieveFileServer
}

// NewMockFileService_RetrieveFileServer creates a new mock instance.
func NewMockFileService_RetrieveFileServer(ctrl *gomock.Controller) *MockFileService_RetrieveFileServer {
	mock := &MockFileService_RetrieveFileServer{ctrl: ctrl}
	mock.recorder = &MockFileService_RetrieveFileServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService_RetrieveFileServer) EXPECT() *MockFileService_RetrieveFileServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockFileService_RetrieveFileServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockFileService_RetrieveFileServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFileService_RetrieveFileServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockFileService_RetrieveFileServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockFileService_RetrieveFileServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFileService_RetrieveFileServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockFileService_RetrieveFileServer) Send(arg0 *grpcapp.RetrieveFileResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockFileService_RetrieveFileServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockFileService_RetrieveFileServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockFileService_RetrieveFileServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockFileService_RetrieveFileServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockFileService_RetrieveFileServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockFileService_RetrieveFileServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockFileService_RetrieveFileServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFileService_RetrieveFileServer)(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockFileService_RetrieveFileServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockFileService_RetrieveFileServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockFileService_RetrieveFileServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockFileService_RetrieveFileServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockFileService_RetrieveFileServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockFileService_RetrieveFileServer)(nil).SetTrailer), arg0)
}

// MockFileService_UploadFileServer is a mock of FileService_UploadFileServer interface.
type MockFileService_UploadFileServer struct {
	ctrl     *gomock.Controller
	recorder *MockFileService_UploadFileServerMockRecorder
}

// MockFileService_UploadFileServerMockRecorder is the mock recorder for MockFileService_UploadFileServer.
type MockFileService_UploadFileServerMockRecorder struct {
	mock *MockFileService_UploadFileServer
}

// NewMockFileService_UploadFileServer creates a new mock instance.
func NewMockFileService_UploadFileServer(ctrl *gomock.Controller) *MockFileService_UploadFileServer {
	mock := &MockFileService_UploadFileServer{ctrl: ctrl}
	mock.recorder = &MockFileService_UploadFileServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService_UploadFileServer) EXPECT() *MockFileService_UploadFileServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockFileService_UploadFileServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockFileService_UploadFileServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockFileService_UploadFileServer) Recv() (*grpcapp.UploadFileParam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*grpcapp.UploadFileParam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockFileService_UploadFileServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockFileService_UploadFileServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockFileService_UploadFileServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).RecvMsg), m)
}

// SendAndClose mocks base method.
func (m *MockFileService_UploadFileServer) SendAndClose(arg0 *grpcapp.UploadFileResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockFileService_UploadFileServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).SendAndClose), arg0)
}

// SendHeader mocks base method.
func (m *MockFileService_UploadFileServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockFileService_UploadFileServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockFileService_UploadFileServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockFileService_UploadFileServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockFileService_UploadFileServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockFileService_UploadFileServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockFileService_UploadFileServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockFileService_UploadFileServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockFileService_UploadFileServer)(nil).SetTrailer), arg0)
}
